
LarsTest01 { ; by Lars Vangsgaard
; good to order 5
  Angle 8
  Axiom [FX][++FX][++++FX][++++++FX]
  X=[+FA][-FW]
;  Y=[+FW][-FA]
  A=[+F][-FZ]
  B=[+F][-FX]
  W=[+FB][-F]
  Z=[+FX][-F]
  }

LarsTest01a { ; by Lars Vangsgaard
; good to order 5, then stops
  Angle 8
  Axiom [C1FX][C1++FX][C1++++FX][C1++++++FX]
  X=[<1+FA][<1-FW]
  Y=[<1+FS][<1-FS]
  A=[<1+F][<1-FZ]
  B=[<1+F][<1-FY]
  W=[<1+FB][<1-F]
  Z=[<1+FY][<1-F]
  S=[<1+F][<1-F]
  }

LarsTest02 { ; by Lars Vangsgaard
; good to order 5
  Angle 8
  Axiom [+FX][+++FX][+++++FX][+++++++FX]
  X=[+FA][-FW]
;  Y=[+FW][-FA]
  A=[+F][-FZ]
  B=[+F][-FX]
  W=[+FB][-F]
  Z=[+FX][-F]
  }

