/*
 * helpdefs.h - WASM stub for the generated help ID definitions
 *
 * Normally generated by the hc help compiler from dos_help/help*.src.
 * For WASM Phase 0 we define all referenced constants with sequential
 * integer values so the code compiles.  The help system itself is
 * non-functional until a later phase.
 *
 * -1 means "help disabled" (runtime value, not a constant here).
 */

#ifndef HELPDEFS_H
#define HELPDEFS_H

/* ------------------------------------------------------------------ */
/* Help screen/mode IDs (helpmode variable)                           */
/* ------------------------------------------------------------------ */
#define HELPMENU            1
#define HELPMAIN            2
#define HELPFRACTALS        3
#define HELPXOPTS           4
#define HELPYOPTS           5
#define HELPZOOM            6
#define HELPSAVEREST        7
#define HELPLOADFILE        8
#define HELPPARMFILE        9
#define HELPCOMMANDS        10
#define HELPVIDEOCHOICE     11
#define HELPVIDSEL          12
#define HELPXHAIR           13
#define HELPCYCLING         14
#define HELPCOLORMAP        15
#define HELPCOORDS          16
#define HELPSCRNCOORDS      17
#define HELPVIEW            18
#define HELPPOPTS           19
#define HELPBROWSE          20
#define HELPBRWSPARMS       21
#define HELPRDS             22
#define HELPEVOL            23
#define HELP3D              24
#define HELP3DMODE          25
#define HELP3DFILL          26
#define HELP3DGLASSES       27
#define HELP3DLIGHT         28
#define HELP3DPARMS         29
#define HELP3DFRACT         30
#define HELP3DOVLY          31
#define HELPSTARFLD         32
#define HELP_ORBITS         33
#define HELP_JIIM           34
#define HELPCOORDS2         35
#define ANTCOMMANDS         36
#define RDSKEYS             37
#define HELP_INDEX          0
#define HELP_VERSION        38
#define INTRO_AUTHORS       50
#define INTRO_CREDITS       51
#define MORE                999

/* ------------------------------------------------------------------ */
/* Fractal help text IDs (fractalspecific[].helptext)                 */
/* These are label values; any unique integer works for compilation.  */
/* ------------------------------------------------------------------ */
#define HF_MANDEL           100
#define HF_JULIA            101
#define HF_MANDELBROTMIX4   102
#define HF_MANDELCLOUD      103
#define HF_JULIA4           104
#define HF_JULZPOWER        105
#define HF_JULZZPWR         106
#define HF_MANZPOWER        107
#define HF_MANZZPWR         108
#define HF_NEWT             109
#define HF_NEWTBAS          110
#define HF_COMPLEXNEWT      111
#define HF_LAMBDA           112
#define HF_LAMBDAFN         113
#define HF_LAMBDAFNFN       114
#define HF_MANDFN           115
#define HF_MANDFNPLUSEXP    116
#define HF_MANDFNPLUSZSQRD  117
#define HF_JULFNPLUSEXP     118
#define HF_JULFNPLUSZSQRD   119
#define HF_MANDEL4          120
#define HF_MARKS            121
#define HF_MARKSMAND        121
#define HF_MARKSJULIA       122
#define HF_MARKSMANDPWR     123
#define HF_CMPLXMARKSMAND   124
#define HF_CMPLXMARKSJUL    125
#define HF_FNPLUSFN         126
#define HF_FNTIMESFN        127
#define HF_FNXZPLUSZ        128
#define HF_FNZTIMESZ        129
#define HF_FNPLUSFNPIX      130
#define HF_JULIAFNFN        131
#define HF_MANLAMFNFN       132
#define HF_MANDELFNFN       133
#define HF_SQRFN            134
#define HF_SQROVFN          135
#define HF_UNITY            136
#define HF_MARTIN           137
#define HF_BARNSM1          138
#define HF_BARNSM2          139
#define HF_BARNSM3          140
#define HF_BARNSJ1          141
#define HF_BARNSJ2          142
#define HF_BARNSJ3          143
#define HF_HALLEY           144
#define HF_CIRCLE           145
#define HF_LORENZ           146
#define HF_LORENZ3D1        147
#define HF_LORENZ3D3        148
#define HF_LORENZ3D4        149
#define HF_HENON            150
#define HF_PICKOVER         151
#define HF_GINGER           152
#define HF_HOPALONG         153
#define HF_QUADRUPTWO       154
#define HF_TIMSERR          155
#define HF_DIFFUS           156
#define HF_LATOO            157
#define HF_ICON             158
#define HF_POPCORN          159
#define HF_POPCJUL          160
#define HF_PLASMA           161
#define HF_SIER             162
#define HF_KAM              163
#define HF_VL               164
#define HF_CELLULAR         165
#define HF_FROTH            166
#define HF_MAGM1            167
#define HF_MAGM2            168
#define HF_MAGJ1            169
#define HF_MAGJ2            170
#define HF_MLAMBDA          171
#define HF_BIFURCATION      172
#define HF_BIFLAMBDA        173
#define HF_BIFPLUSSINPI     174
#define HF_BIFEQSINPI       175
#define HF_BIFMAY           176
#define HF_BIFSTEWART       177
#define HF_DIVIDEBROT5      178
#define HF_ROSS             179
#define HF_DYNAM            180
#define HF_CHIP             181
#define HF_HYPERC           182
#define HF_HYPERCJ          183
#define HF_QUAT             184
#define HF_QUATJ            185
#define HF_ESCHER           186
#define HF_PHOENIX          187
#define HF_PHOENIXCPLX      188
#define HF_MANDPHOENIX      189
#define HF_MANDPHOENIXCPLX  190
#define HF_TETRATE          191
#define HF_THREEPLY         192
#define HF_SPIDER           193
#define HF_TEST             194
#define HF_MANOWAR          195
#define HF_MANOWARJ         196
#define HF_ANT              197
#define HF_INVERSE          198

/* ------------------------------------------------------------------ */
/* Fractal type parameter IDs (fractalspecific[].helpformula)         */
/* ------------------------------------------------------------------ */
#define HT_MANDEL           200
#define HT_JULIA            201
#define HT_MANDELBROTMIX4   202
#define HT_MANDELCLOUD      203
#define HT_MANDEL4          204  /* reuse via HT_MANDJUL4 */
#define HT_MANDJUL4         204
#define HT_MANZPOWER        205
#define HT_NEWT             206
#define HT_NEWTBAS          207
#define HT_NEWTCMPLX        208
#define HT_LAMBDA           209
#define HT_LAMBDAFN         210
#define HT_MLAMBDA          211
#define HT_MANDFN           212
#define HT_FNORFN           213
#define HT_MARKS            214
#define HT_MARTIN           215
#define HT_BARNS            216
#define HT_HALLEY           217
#define HT_CIRCLE           218
#define HT_LORENZ           219
#define HT_HENON            220
#define HT_PICK             221
#define HT_PICKMJ           222
#define HT_DIFFUS           223
#define HT_LATOO            224
#define HT_ICON             225
#define HT_POPCORN          226
#define HT_PLASMA           227
#define HT_SIER             228
#define HT_KAM              229
#define HT_VL               230
#define HT_CELLULAR         231
#define HT_FROTH            232
#define HT_MAGNET           233
#define HT_JULIBROT         234
#define HT_BIF              235
#define HT_DIVIDEBROT5      236
#define HT_ROSS             237
#define HT_DYNAM            238
#define HT_HYPERC           239
#define HT_QUAT             240
#define HT_ESCHER           241
#define HT_PHOENIX          242
#define HT_LYAPUNOV         243
#define HT_TEST             244
#define HT_ANT              245
#define HT_INVERSE          246
#define HT_SCOTSKIN         247
#define HT_GINGER           248
#define HT_ARROW            249
#define HT_ARROW_2          250
#define HT_FORMULA          251
#define HT_IFS              252
#define HT_LSYS             253
#define HT_UNITY            254

#endif /* HELPDEFS_H */
